source 'https://rubygems.org'
gem 'jekyll', '2.5.2'
gem 'jekyll-assets', '1.0.0'
gem 'jekyll-feed', '0.3.1'
gem 'jekyll-less', '0.0.4'
gem 'jekyll-redirect-from', '0.8.0'
gem 'jekyll-sitemap', '0.9.0'
gem 'jemoji', '0.5.0'
gem 'uglifier', '2.7.2'
gem 'therubyracer', '0.12.2'
gem 'autoprefixer-rails'
